- hosts:
  - ec2-swarm-m2
  - ec2-swarm-m3
  become: yes
  tasks:
    - shell: docker swarm leave --force
    
    - name: "Fazendo join swarm master no master"
      shell: 

    - shell: docker node ls
      register: ps
    - debug:
        msg: " '{{ ps.stdout_lines }}' "
