apiVersion: v1
kind: Pod
metadata:
  name: pod-javadb
  labels:
    app: pod-javadb
spec:
  containers:
    - name: container-pod-javadb
      image: didox/crud-java-login:v0.0.1
      # env:
      #   - name: USER
      #     value: root
      #   - name: PASSWORD
      #     value: password_mysql
      #   - name: DATABASE_URL
      #     value: mysql://mysql:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
      #     # value: mysql://10.111.41.255:3306/SpringWebYoutubeTest?useTimezone=true&serverTimezone=UTC
      ports:
        - containerPort: 8080