apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
spec:
  template:
    metadata:
      name: pod-javadb
      labels:
        app: pod-javadb
    spec:
      containers:
        - name: container-pod-javadb
          image: didox/crud-java-login:v0.0.1
          env:
            - name: USER
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: USER
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: PASSWORD
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: DATABASE_URL
          ports:
            - containerPort: 8080
  replicas: 2
  selector:
    matchLabels:
      app: pod-javadb


# $ kubectl logs -l app=lable-pod-java # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-java