# Cria recurso externo do cluster, pode ser utilizado um nginx com proxypass para um unico IP

apiVersion: v1
kind: Service
metadata:
  name: nodeport-pod-nginx
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30000 # 30000 ~ 32767
  selector:
    app: didox-nginx

# kubectl apply -f node-port-nginx.yml
# kubectl describe -f node-port-nginx.yml
# kubectl delete -f node-port-nginx.yml