apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
spec:
  template:
    metadata:
      name: pod-nodejs
      labels:
        app: lable-pod-nodejs
    spec:
      containers:
        - name: container-nodejs
          image: didox/app-imersao-docker-nodejs
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "512Mi" # 512 MB
              cpu: "0.5" # 1 milicors VCPU # este recurso tira do meu cluster este recurso #https://www.datacenters.com/news/what-is-a-vcpu-and-how-do-you-calculate-vcpu-to-cpu https://www.hyve.com/what-is-a-vmware-vcpu/
            limits: # caso a aplicação precise de mais recurso, ele coloca este limite automático
              memory: "800Mi" # 512 MB
              cpu: "1"
  replicas: 3
  selector:
    matchLabels:
      app: lable-pod-nodejs