- hosts: all
  tasks:
    - name: "Configurando containerd config no diretorio etc"
      shell: mkdir -p /etc/containerd && containerd config default > /etc/containerd/config.toml
      become: yes

    - name: "Restart Containerd"
      shell: systemctl restart containerd
      become: yes

    - name: "Reseta workers no cluster master"
      shell: kubeadm reset --force
      become: yes

    - name: "Adiciona workers no cluster master"
      shell: kubeadm join 172.31.4.4:6443 --token 1b7ht3.shv0hr4feg5n3gq3 --discovery-token-ca-cert-hash sha256:f0276e6b3a50cb400de9701c39828ab83caef0caf725bfc7a61f6960db595903
      become: yes