- hosts: all
  become: yes
  tasks:
    - name: "Create dabatase"
      shell: echo "create database SpringWebYoutube;"| kubectl exec -it mysql-6886bfcbcd-n5k62  --tty -- mysql -uroot -ppassword_mysql 
    
    - name: "Restore dump"
      shell: cat /root/k8s-deploy/1.2-dump-mysql.sql  | kubectl exec -it mysql-6886bfcbcd-n5k62  --tty -- mysql -uroot -ppassword_mysql SpringWebYoutube
