apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deployment
  # namespace: umnamespace # para colocar em um namespace diferente
spec:
  template:
    metadata:
      name: pod-nodejs
      labels:
        app: lable-pod-nodejs
    spec:
      containers:
        - name: container-nodejs
          image: didox/app-imersao-docker-nodejs
          ports:
            - containerPort: 3000
          # env:
          #   - name: "DATABASE_URLS"
          #     value: "https://usuario@senha:mysql.server:3306"
  replicas: 3
  selector:
    matchLabels:
      app: lable-pod-nodejs


# $ kubectl apply -f deployment-nodejs.yml
# $ kubectl describe -f deployment-nodejs.yml
# $ kubectl delete -f deployment-nodejs.yml
# $ kubectl logs -l app=lable-pod-nodejs # log de todos os lables do replicaset
# $ kubectl logs --tail=20 --follow=true -l app=lable-pod-nodejs
# $ kubectl rollout history deployment
# $ kubectl annotate deployment.apps/nodejs-deployment kubernetes.io/change-cause="levantando mudando a variavel de ambiente"
# $ kubectl rollout undo deployment.apps/nodejs-deployment --to-revision=2
# $ kubectl scale deployment.v1.apps/nodejs-deployment --replicas=2

# $ kubectl autoscale deployment.v1.apps/nodejs-deployment --min=2 --max=5 --cpu-percent=80


# $ kubectl get pod -o yaml > teste.yml # exportando yaml do pod do kubernets


# $ kubectl apply -f deployment-site.yaml
# $ kubectl delete -f deployment-site.yaml
# $ kubectl get deployment
# $ kubectl describe deployment site-deployment
# $ kubectl rollout history deployment site-deployment
# $ kubectl annotate deployment.v1.apps/site-deployment kubernetes.io/change-cause="teste de comentário"
# $ kubectl rollout undo deployment.v1.apps/site-deployment --to-revision=2
# $ kubectl get rs
# $ kubectl get rs -w
# $ kubectl get pods -o wide
# $ kubectl scale deployment.v1.apps/site-deployment --replicas=2
# $ kubectl autoscale deployment.v1.apps/site-deployment --min=5 --max=8 --cpu-percent=80
# $ kubectl get hpa # mostra status autoscale
# $ kubectl delete hpa site-deployment
# $ kubectl delete horizontalpodautoscaler --all
# $ kubectl set image deployment.v1.apps/site-deployment nginx=nginx:latest
# $ kubectl run didox-nginx-memoria --image=nginx --requests=cpu=500m,memory=500M --expose --port=80
# $ kubectl autoscale deployment didox-nginx-memoria --cpu-percent=50 --min=1 --max=10
# $ kubectl create namespace bancodedados # cria namespaces para organizar seus pods e recursos
# $ kubectl get pods -n bancodedados # lista recursos do namespace
